FROM aflplusplus/aflplusplus:v4.32c

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        build-essential \
        ca-certificates \
        cmake \
        bsdmainutils \
        make \
    && rm -rf /var/lib/apt/lists/*

# install zzuf
RUN git clone https://github.com/samhocevar/zzuf.git && cd zzuf && ./bootstrap && ./configure && make && make install

WORKDIR /workspace

CMD ["bash"]
