services:
  aflplusplus:
    image: imperial-fuzzing-aflplusplus-2026:pre-session
    build:
      context: .
      dockerfile: Dockerfile.aflplusplus
    working_dir: /workspace
    stdin_open: true
    tty: true
    volumes:
      - ./challenges:/workspace/challenges
