services:
  semgrep:
    build: .
    image: kalmarnotes-semgrep:latest
    volumes:
      - ../../session_1/in-class/kalmarnotes:/levels:ro
      - ./custom_level1:/custom_level1:ro
      - .:/workspace:ro
      - ./reports:/scan/reports
    environment:
      SEMGREP_SEND_METRICS: "off"
